import type { KnowledgeAdminRuntimeOptions } from "@/features/knowledge/knowledgeAdminRuntimeTypes";
import { useKnowledgeAdminActions } from "@/features/knowledge/useKnowledgeAdminActions";
import { useKnowledgeAdminReset } from "@/features/knowledge/useKnowledgeAdminReset";
import { useKnowledgeAdminState } from "@/features/knowledge/useKnowledgeAdminState";
import { isDocumentBatchRebuildEligible } from "@/features/knowledge/useKnowledgeDocumentIndexState";
import { useKnowledgeRuntimeSlices } from "@/features/knowledge/useKnowledgeRuntimeSlices";
import { clearPaginationState } from "@/utils/pagination";

export function useKnowledgeAdminRuntime(options: KnowledgeAdminRuntimeOptions) {
  const knowledgeAdminState = useKnowledgeAdminState();
  const {
    adminDocuments,
    adminFolderOptions,
    adminFolders,
    adminImportJobs,
    adminKnowledgeBaseOptions,
    adminKnowledgeBases,
    documentChunkPagination,
    documentIndexForm,
    documentIndexVersionPagination,
    documentManagerModalOpen,
    documentModalMode,
    documentPagination,
    documentPermissionForm,
    documentSearchForm,
    documentVersionPagination,
    failedIndexJobPagination,
    failedIndexJobs,
    folderCreateForm,
    folderDangerForm,
    folderEditForm,
    folderModalMode,
    folderPagination,
    importAdminBusy,
    importAdminFeedback,
    importFileInputKey,
    importJobPagination,
    importSearchForm,
    importUploadForm,
    indexRetryForm,
    knowledgeBaseCreateForm,
    knowledgeBaseDangerForm,
    knowledgeBaseEditForm,
    knowledgeBaseIndexForm,
    knowledgeBaseModalMode,
    knowledgeBasePagination,
    knowledgeBasePermissionForm,
    knowledgeBaseSearchForm,
    selectedDocumentId,
    selectedFailedIndexJobIds,
    selectedFolderId,
    selectedImportFiles,
    selectedKnowledgeBaseDetail,
    selectedKnowledgeBaseId,
  } = knowledgeAdminState;

  const {
    documentIndexState,
    documentSelection,
    failedIndexJobState,
    knowledgeDerivedState,
    knowledgePermissionState,
  } = useKnowledgeRuntimeSlices({
    knowledgeAdminState,
    runtimeOptions: options,
  });
  const {
    allBatchRebuildEligibleDocumentsSelected,
    allCleanupEligibleIndexVersionsSelected,
    batchRebuildEligibleDocuments,
    cleanupEligibleIndexVersions,
    clearBatchDocumentSelection,
    clearIndexVersionCleanupSelection,
    clearSelectedDocumentDetails,
    highlightedDocumentChunkId,
    onAllBatchDocumentsToggle,
    onAllIndexVersionsForCleanupToggle,
    onBatchDocumentSelectionToggle,
    onIndexVersionCleanupSelectionToggle,
    pruneSelectedBatchDocuments,
    pruneSelectedIndexVersionsForCleanup,
    selectDocumentChunk,
    selectedAdminDocumentDetail,
    selectedBatchDocumentIds,
    selectedBatchDocumentSet,
    selectedBatchRebuildDocumentIds,
    selectedCleanupIndexVersionIds,
    selectedCleanupIndexVersionSet,
    selectedCleanupPendingDeleteIndexVersionIds,
    selectedDocumentChunks,
    selectedDocumentIndexVersions,
    selectedDocumentVersions,
  } = documentSelection;
  const {
    activeFolders,
    activeKnowledgeBases,
    folderParentOptions,
    selectedAdminDocument,
    selectedDocumentForDisplay,
    selectedFolder,
    selectedImportKnowledgeBase,
    selectedKnowledgeBase,
  } = knowledgeDerivedState;
  const {
    buildDepartmentKnowledgeBaseAccessRules,
    canCreateFolder,
    canCreateKnowledgeBase,
    canDeleteSelectedFolder,
    canDeleteSelectedKnowledgeBase,
    canRebuildSelectedKnowledgeBaseIndex,
    canReplaceSelectedDocumentPermissions,
    canReplaceSelectedKnowledgeBasePermissions,
    canUpdateSelectedFolder,
    canUpdateSelectedKnowledgeBase,
    canUploadImportFiles,
    documentPermissionParentConflict,
    importUploadPermissionParentConflict,
    resetKnowledgeBaseCreateForm,
    selectedDocumentParentKnowledgeBase,
    syncDocumentPermissionForm,
    syncFolderEditForm,
    syncKnowledgeBaseCreateOwnerDefault,
    syncKnowledgeBaseEditForm,
    syncKnowledgeBasePermissionForm,
  } = knowledgePermissionState;
  const {
    canCleanupSelectedIndexVersions,
    canRebuildSelectedDocumentIndex,
    canRebuildSelectedDocumentsIndex,
  } = documentIndexState;
  const {
    canRetrySelectedFailedIndexJobs,
    failedIndexJobDocumentCount,
    failedIndexJobStageSummary,
    selectedFailedIndexJobSet,
  } = failedIndexJobState;

  const knowledgeBaseActions = useKnowledgeAdminActions({
    documentIndexState,
    documentSelection,
    failedIndexJobState,
    knowledgeAdminState,
    knowledgeDerivedState,
    knowledgePermissionState,
    runtimeOptions: options,
  });

  const { clearKnowledgeAdminState, clearKnowledgeBaseOptions } = useKnowledgeAdminReset({
    adminDocuments,
    adminFolderOptions,
    adminFolders,
    adminImportJobs,
    adminKnowledgeBaseOptions,
    adminKnowledgeBases,
    clearPaginationState,
    clearSelectedDocumentDetails,
    clearSelectedDocumentMetadata: knowledgeBaseActions.clearSelectedDocumentMetadata,
    documentIndexForm,
    documentManagerModalOpen,
    documentModalMode,
    documentPagination,
    documentPermissionForm,
    documentSearchForm,
    failedIndexJobPagination,
    failedIndexJobs,
    folderDangerForm,
    folderModalMode,
    folderPagination,
    importAdminFeedback,
    importJobPagination,
    importSearchForm,
    importUploadForm,
    indexRetryForm,
    knowledgeBaseDangerForm,
    knowledgeBaseIndexForm,
    knowledgeBaseModalMode,
    knowledgeBasePagination,
    knowledgeBasePermissionForm,
    knowledgeBaseSearchForm,
    selectedBatchDocumentIds,
    selectedDocumentId,
    selectedFailedIndexJobIds,
    selectedFolderId,
    selectedImportFiles,
    selectedKnowledgeBaseDetail,
    selectedKnowledgeBaseId,
  });

  return {
    ...knowledgeBaseActions,
    activeFolders,
    activeKnowledgeBases,
    adminDocuments,
    adminFolders,
    adminFolderOptions,
    adminImportJobs,
    adminKnowledgeBaseOptions,
    adminKnowledgeBases,
    allBatchRebuildEligibleDocumentsSelected,
    allCleanupEligibleIndexVersionsSelected,
    batchRebuildEligibleDocuments,
    canCleanupSelectedIndexVersions,
    canCreateFolder,
    canCreateKnowledgeBase,
    canDeleteSelectedFolder,
    canDeleteSelectedKnowledgeBase,
    canRebuildSelectedDocumentIndex,
    canRebuildSelectedDocumentsIndex,
    canRebuildSelectedKnowledgeBaseIndex,
    canReplaceSelectedDocumentPermissions,
    canReplaceSelectedKnowledgeBasePermissions,
    canRetrySelectedFailedIndexJobs,
    canUpdateSelectedFolder,
    canUpdateSelectedKnowledgeBase,
    canUploadImportFiles,
    cleanupEligibleIndexVersions,
    clearKnowledgeAdminState,
    clearKnowledgeBaseOptions,
    documentChunkPagination,
    documentIndexForm,
    documentIndexVersionPagination,
    documentManagerModalOpen,
    documentModalMode,
    documentPagination,
    documentPermissionForm,
    documentPermissionParentConflict,
    documentSearchForm,
    documentVersionPagination,
    failedIndexJobDocumentCount,
    failedIndexJobPagination,
    failedIndexJobStageSummary,
    failedIndexJobs,
    folderCreateForm,
    folderDangerForm,
    folderEditForm,
    folderModalMode,
    folderPagination,
    folderParentOptions,
    highlightedDocumentChunkId,
    importAdminBusy,
    importAdminFeedback,
    importFileInputKey,
    importJobPagination,
    importSearchForm,
    importUploadForm,
    importUploadPermissionParentConflict,
    indexRetryForm,
    isDocumentBatchRebuildEligible,
    knowledgeBaseCreateForm,
    knowledgeBaseDangerForm,
    knowledgeBaseEditForm,
    knowledgeBaseIndexForm,
    knowledgeBaseModalMode,
    knowledgeBasePagination,
    knowledgeBasePermissionForm,
    knowledgeBaseSearchForm,
    onAllBatchDocumentsToggle,
    onAllIndexVersionsForCleanupToggle,
    onBatchDocumentSelectionToggle,
    onIndexVersionCleanupSelectionToggle,
    selectDocumentChunk,
    selectedAdminDocument,
    selectedBatchDocumentSet,
    selectedBatchRebuildDocumentIds,
    selectedCleanupIndexVersionSet,
    selectedCleanupPendingDeleteIndexVersionIds,
    selectedDocumentChunks,
    selectedDocumentForDisplay,
    selectedDocumentId,
    selectedDocumentIndexVersions,
    selectedDocumentParentKnowledgeBase,
    selectedDocumentVersions,
    selectedFailedIndexJobIds,
    selectedFailedIndexJobSet,
    selectedFolder,
    selectedFolderId,
    selectedImportFiles,
    selectedImportKnowledgeBase,
    selectedKnowledgeBase,
    selectedKnowledgeBaseDetail,
    syncKnowledgeBaseCreateOwnerDefault,
  };
}
