import type { SetupFormModel } from "@/features/setup/setupModel";

// 内置角色在初始化时一次性创建，后续权限扩展应通过管理端配置或迁移脚本演进。
export const BUILTIN_ROLES = [
  "system_admin",
  "security_admin",
  "audit_admin",
  "department_admin",
  "knowledge_base_admin",
  "employee",
];

export function createDefaultSetupForm(): SetupFormModel {
  // 默认值面向本地 docker-compose 演示环境；生产部署应在页面中替换为真实服务地址和模型名称。
  return {
    setupToken: "",
    adminUsername: "admin",
    adminDisplayName: "系统管理员",
    adminPassword: "",
    adminPasswordConfirm: "",
    adminEmail: "admin@example.com",
    adminPhone: "",
    enterpriseName: "默认企业",
    enterpriseCode: "default",
    departmentName: "默认部门",
    departmentCode: "default",
    secretProviderEndpoint: "postgres://local-secrets",
    redisUrl: "redis://redis:6379/0",
    minioEndpoint: "http://minio:9000",
    minioBucket: "little-bear-rag",
    minioRegion: "local",
    minioAccessKeyRef: "secret://rag/minio/access-key",
    minioSecretKeyRef: "secret://rag/minio/secret-key",
    objectKeyPrefix: "p0/",
    qdrantBaseUrl: "http://qdrant:6333",
    qdrantApiKeyRef: "",
    collectionPrefix: "little_bear_p0",
    vectorDistance: "cosine",
    keywordLanguage: "zh",
    keywordAnalyzer: "zhparser",
    modelGatewayMode: "external",
    embeddingProviderBaseUrl: "http://tei-embedding:80",
    embeddingProviderApiKey: "",
    rerankProviderBaseUrl: "http://tei-rerank:80",
    rerankProviderApiKey: "",
    llmProviderBaseUrl: "",
    llmProviderApiKey: "",
    embeddingDimension: 768,
    embeddingModel: "jina‑embeddings‑v2‑base‑zh",
    rerankModel: "bge-reranker-base",
    llmModel: "qwen3-4b",
    llmFallbackModel: "qwen3-4b",
    llmTemperature: 0.1,
    llmMaxTokens: 800,
    llmFirstTokenTimeoutMs: 3000,
    llmTotalTimeoutMs: 20000,
    llmMaxRetries: 0,
    llmRetryBackoffMs: 0,
    llmEnableThinking: false,
    passwordMinLength: 12,
    accessTokenTtlMinutes: 30,
    refreshTokenTtlMinutes: 10080,
    jwtIssuer: "little-bear-rag",
    jwtAudience: "little-bear-internal",
    jwtSigningKeyRef: "secret://rag/auth/jwt-signing-key",
    vectorTopK: 20,
    keywordTopK: 20,
    rerankInputTopK: 20,
    rerankMinScore: 0.05,
    finalContextTopK: 8,
    maxContextTokens: 1500,
    chunkDefaultSizeTokens: 800,
    chunkOverlapTokens: 120,
    chunkStrategyMode: "heading_paragraph",
    chunkPreserveTables: true,
    chunkPreserveCodeBlocks: true,
    chunkPreserveContractClauses: true,
    maxFileMb: 50,
    maxConcurrentJobs: 4,
    embeddingBatchSize: 32,
    indexBatchSize: 128,
    queryEmbeddingEnabled: true,
    retrievalResultEnabled: true,
    finalAnswerEnabled: false,
    crossUserFinalAnswerAllowed: false,
    queryQpsPerUser: 2,
    auditRetentionDays: 180,
    auditQueryTextMode: "hash",
    permissionDefaultVisibility: "department",
    permissionCacheTtlSeconds: 300,
    permissionWriteAccessBlockFirst: true,
    permissionBlockOldIndexRefs: true,
    permissionFailClosed: true,
    securityRequireCitation: true,
    securityBlockInternalPromptLeakage: true,
    securityBlockSecretRefLeakage: true,
    securityPiiRedactionEnabled: true,
    securityRedactLogs: true,
    securityRedactAuditSummary: true,
    timeoutQueryTotalMs: 8000,
    timeoutAuthPermissionMs: 100,
    timeoutRewriteMs: 300,
    timeoutEmbeddingMs: 3000,
    timeoutVectorSearchMs: 500,
    timeoutKeywordSearchMs: 500,
    timeoutRerankMs: 3000,
    timeoutContextMs: 200,
    timeoutPostprocessMs: 300,
    degradeRewriteTimeout: "use_original_query",
    degradeEmbeddingTimeout: "keyword_only",
    degradeVectorUnavailable: "keyword_and_metadata",
    degradeKeywordUnavailable: "vector_and_metadata",
    degradeRerankTimeout: "fusion_score",
    degradeLlmTimeout: "return_retrieval_with_citations",
    degradeModelPoolOverloaded: "return_retryable_degraded_response",
    degradeImportBacklog: "slow_down_import",
    observabilityMetricsEnabled: true,
    observabilityTraceEnabled: true,
    alertActiveConfigLoadFailed: 1,
    alertPermissionViolationRate: 0,
    alertDraftIndexExposureCount: 0,
    alertImportFailureRate: 0.1,
    alertWorkerQueueBacklog: 100,
    alertLlmTimeoutRate: 0.2,
  };
}
