import type { FieldSection } from "@/features/setup/setupFieldTypes";

// 认证、权限、安全、超时、降级和可观测性字段。
export const policySection: FieldSection = {
  title: "认证与运行策略",
  fields: [
    { key: "passwordMinLength", label: "密码最小长度", input: "number", hint: "用于约束本地账号密码强度；生产环境建议不低于 12 位。", min: 8, step: 1, required: true },
    {
      key: "accessTokenTtlMinutes",
      label: "访问令牌有效期（分钟）",
      input: "number",
      hint: "Access token 的有效期；较短有效期可降低令牌泄露后的暴露窗口。",
      min: 1,
      step: 1,
      required: true,
    },
    {
      key: "refreshTokenTtlMinutes",
      label: "刷新令牌有效期（分钟）",
      input: "number",
      hint: "Refresh token 的有效期；应结合组织安全策略和会话体验设定。",
      min: 1,
      step: 1,
      required: true,
    },
    { key: "jwtIssuer", label: "JWT 签发方", input: "text", hint: "用于声明访问令牌签发主体，并参与令牌校验。", required: true },
    { key: "jwtAudience", label: "JWT 受众", input: "text", hint: "用于声明访问令牌适用范围，并参与令牌校验。", required: true },
    { key: "jwtSigningKeyRef", label: "JWT 签名密钥引用", input: "text", hint: "填写 Secret Store 中的签名密钥引用；真实密钥不得写入 active config。", span: "full", required: true },
    { key: "maxFileMb", label: "文件大小上限 MB", input: "number", hint: "单个导入文件允许的最大体积。", min: 1, step: 1 },
    { key: "maxConcurrentJobs", label: "最大并发任务数", input: "number", hint: "系统级导入任务并发上限，用于保护模型服务和索引服务容量。", min: 1, step: 1 },
    { key: "embeddingBatchSize", label: "向量化批大小", input: "number", hint: "单次 embedding 请求处理的片段数量；应结合 provider 吞吐与延迟设定。", min: 1, step: 1 },
    { key: "indexBatchSize", label: "索引写入批大小", input: "number", hint: "单批写入向量索引和关键词索引的片段数量。", min: 1, step: 1 },
    { key: "queryQpsPerUser", label: "单用户查询 QPS", input: "number", hint: "单用户查询限流阈值，用于保护检索链路和模型服务。", min: 1, step: 1 },
    { key: "auditRetentionDays", label: "审计保留天数", input: "number", hint: "审计数据保留周期；应符合组织合规和数据治理要求。", min: 1, step: 1 },
    {
      key: "auditQueryTextMode",
      label: "查询文本记录方式",
      input: "select",
      hint: "控制审计记录中对查询文本的保存方式；生产环境应优先选择 hash 或 none。",
      options: [
        { label: "none", value: "none" },
        { label: "hash", value: "hash" },
        { label: "plain", value: "plain" },
      ],
    },
  ],
};

export const advancedConfigSection: FieldSection = {
  title: "高级运行策略",
  fields: [
    { key: "llmTemperature", label: "LLM temperature", input: "number", hint: "控制答案生成随机性；越低越稳定，越高越发散。", min: 0, step: 0.01 },
    { key: "llmMaxTokens", label: "LLM 最大输出 Token", input: "number", hint: "单次答案生成允许输出的最大 token 数。", min: 1, step: 1 },
    { key: "llmFirstTokenTimeoutMs", label: "首 token 超时 ms", input: "number", hint: "模型首 token 等待预算；当前作为配置契约保存，流式链路可逐步接入。", min: 1, step: 1 },
    { key: "llmTotalTimeoutMs", label: "LLM 总超时 ms", input: "number", hint: "答案生成调用的整体超时预算。", min: 1, step: 1 },
    { key: "llmMaxRetries", label: "LLM 最大重试次数", input: "number", hint: "LLM provider 调用失败后的最大重试次数；0 表示不重试。", min: 0, step: 1 },
    { key: "llmRetryBackoffMs", label: "LLM 重试退避 ms", input: "number", hint: "LLM 重试之间的退避时间。", min: 0, step: 1 },
    { key: "llmEnableThinking", label: "启用 thinking 参数", input: "checkbox", hint: "写入 OpenAI-compatible extra body 的 chat_template_kwargs.enable_thinking。", group: "llm-switch" },
    {
      key: "permissionDefaultVisibility",
      label: "默认文档可见性",
      input: "select",
      hint: "新建或导入资源未显式指定权限时使用的默认可见性。",
      options: [
        { label: "部门可见", value: "department" },
        { label: "企业可见", value: "enterprise" },
      ],
    },
    { key: "permissionCacheTtlSeconds", label: "权限缓存 TTL 秒", input: "number", hint: "权限上下文缓存有效期。", min: 1, step: 1 },
    { key: "permissionWriteAccessBlockFirst", label: "收紧权限前先阻断写访问", input: "checkbox", hint: "权限收紧时优先阻断旧写入路径。", group: "permission-tightening" },
    { key: "permissionBlockOldIndexRefs", label: "阻断旧索引引用", input: "checkbox", hint: "权限收紧后阻断旧索引 payload 被继续引用。", group: "permission-tightening" },
    { key: "permissionFailClosed", label: "权限失败时关闭访问", input: "checkbox", hint: "权限计算异常时按拒绝访问处理。", group: "permission-tightening" },
    { key: "securityRequireCitation", label: "强制引用校验", input: "checkbox", hint: "答案必须通过引用来源校验，否则进入降级响应。", group: "security-switch" },
    { key: "securityBlockInternalPromptLeakage", label: "阻断内部提示词泄露", input: "checkbox", hint: "生成后处理阶段阻断内部提示词外泄。", group: "security-switch" },
    { key: "securityBlockSecretRefLeakage", label: "阻断 Secret 引用泄露", input: "checkbox", hint: "生成后处理阶段阻断 secret:// 引用外泄。", group: "security-switch" },
    { key: "securityPiiRedactionEnabled", label: "启用 PII 脱敏", input: "checkbox", hint: "对日志、审计摘要等可观测数据执行敏感信息脱敏。", group: "security-switch" },
    { key: "securityRedactLogs", label: "日志脱敏", input: "checkbox", hint: "写入普通日志前执行脱敏。", group: "security-switch" },
    { key: "securityRedactAuditSummary", label: "审计摘要脱敏", input: "checkbox", hint: "写入审计摘要前执行脱敏。", group: "security-switch" },
    { key: "timeoutQueryTotalMs", label: "查询总超时 ms", input: "number", hint: "一次问答请求的总预算。", min: 1, step: 1 },
    { key: "timeoutAuthPermissionMs", label: "鉴权权限超时 ms", input: "number", hint: "认证和权限上下文计算预算。", min: 1, step: 1 },
    { key: "timeoutRewriteMs", label: "改写超时 ms", input: "number", hint: "查询改写阶段预算。", min: 1, step: 1 },
    { key: "timeoutEmbeddingMs", label: "Embedding 超时 ms", input: "number", hint: "查询向量化调用预算。", min: 1, step: 1 },
    { key: "timeoutVectorSearchMs", label: "向量检索超时 ms", input: "number", hint: "向量库查询预算。", min: 1, step: 1 },
    { key: "timeoutKeywordSearchMs", label: "关键词检索超时 ms", input: "number", hint: "关键词检索预算。", min: 1, step: 1 },
    { key: "timeoutRerankMs", label: "Rerank 超时 ms", input: "number", hint: "重排模型调用预算。", min: 1, step: 1 },
    { key: "timeoutContextMs", label: "上下文构建超时 ms", input: "number", hint: "引用片段组装和裁剪预算。", min: 1, step: 1 },
    { key: "timeoutPostprocessMs", label: "后处理超时 ms", input: "number", hint: "答案清洗、引用校验等后处理预算。", min: 1, step: 1 },
    {
      key: "degradeRewriteTimeout",
      label: "改写超时降级",
      input: "select",
      hint: "查询改写超时时采用的降级动作。",
      options: [
        { label: "使用原始问题", value: "use_original_query" },
        { label: "终止查询", value: "fail_query" },
      ],
    },
    {
      key: "degradeEmbeddingTimeout",
      label: "Embedding 超时降级",
      input: "select",
      hint: "查询向量化不可用时采用的降级动作。",
      options: [
        { label: "仅关键词检索", value: "keyword_only" },
        { label: "仅元数据检索", value: "metadata_only" },
        { label: "终止查询", value: "fail_query" },
      ],
    },
    {
      key: "degradeVectorUnavailable",
      label: "向量不可用降级",
      input: "select",
      hint: "向量库不可用时采用的降级动作。",
      options: [
        { label: "关键词和元数据", value: "keyword_and_metadata" },
        { label: "仅关键词检索", value: "keyword_only" },
        { label: "终止查询", value: "fail_query" },
      ],
    },
    {
      key: "degradeKeywordUnavailable",
      label: "关键词不可用降级",
      input: "select",
      hint: "关键词检索不可用时采用的降级动作。",
      options: [
        { label: "向量和元数据", value: "vector_and_metadata" },
        { label: "仅向量检索", value: "vector_only" },
        { label: "终止查询", value: "fail_query" },
      ],
    },
    {
      key: "degradeRerankTimeout",
      label: "Rerank 超时降级",
      input: "select",
      hint: "重排不可用时采用的降级动作。",
      options: [
        { label: "使用融合分数", value: "fusion_score" },
        { label: "跳过重排", value: "skip_rerank" },
        { label: "终止查询", value: "fail_query" },
      ],
    },
    {
      key: "degradeLlmTimeout",
      label: "LLM 超时降级",
      input: "select",
      hint: "答案生成不可用时采用的降级动作。",
      options: [
        { label: "返回检索结果与引用", value: "return_retrieval_with_citations" },
        { label: "返回无答案原因", value: "return_no_answer_with_reason" },
        { label: "终止查询", value: "fail_query" },
      ],
    },
    {
      key: "degradeModelPoolOverloaded",
      label: "模型池过载降级",
      input: "select",
      hint: "模型服务过载时采用的降级动作。",
      options: [
        { label: "返回可重试降级响应", value: "return_retryable_degraded_response" },
        { label: "进入队列等待", value: "queue_request" },
        { label: "终止查询", value: "fail_query" },
      ],
    },
    {
      key: "degradeImportBacklog",
      label: "导入积压降级",
      input: "select",
      hint: "导入队列积压时采用的降级动作。",
      options: [
        { label: "放慢导入", value: "slow_down_import" },
        { label: "拒绝新导入", value: "reject_new_import" },
        { label: "仅入队等待", value: "queue_only" },
      ],
    },
    { key: "observabilityMetricsEnabled", label: "启用 Metrics", input: "checkbox", hint: "启用指标采集。", group: "observability-switch" },
    { key: "observabilityTraceEnabled", label: "启用 Trace", input: "checkbox", hint: "启用链路追踪。", group: "observability-switch" },
    { key: "alertActiveConfigLoadFailed", label: "配置加载失败阈值", input: "number", hint: "active config 加载失败告警阈值。", min: 0, step: 1 },
    { key: "alertPermissionViolationRate", label: "权限违规率阈值", input: "number", hint: "权限违规率告警阈值。", min: 0, step: 0.01 },
    { key: "alertDraftIndexExposureCount", label: "草稿索引暴露阈值", input: "number", hint: "草稿索引暴露次数告警阈值。", min: 0, step: 1 },
    { key: "alertImportFailureRate", label: "导入失败率阈值", input: "number", hint: "导入失败率告警阈值。", min: 0, step: 0.01 },
    { key: "alertWorkerQueueBacklog", label: "Worker 队列积压阈值", input: "number", hint: "后台任务队列积压告警阈值。", min: 0, step: 1 },
    { key: "alertLlmTimeoutRate", label: "LLM 超时率阈值", input: "number", hint: "LLM 超时率告警阈值。", min: 0, step: 0.01 },
  ],
};
