export interface SetupFormModel {
  setupToken: string;
  adminUsername: string;
  adminDisplayName: string;
  adminPassword: string;
  adminPasswordConfirm: string;
  adminEmail: string;
  adminPhone: string;
  enterpriseName: string;
  enterpriseCode: string;
  departmentName: string;
  departmentCode: string;
  secretProviderEndpoint: string;
  redisUrl: string;
  minioEndpoint: string;
  minioBucket: string;
  minioRegion: string;
  minioAccessKeyRef: string;
  minioSecretKeyRef: string;
  objectKeyPrefix: string;
  qdrantBaseUrl: string;
  qdrantApiKeyRef: string;
  collectionPrefix: string;
  vectorDistance: "cosine" | "dot" | "euclidean";
  keywordLanguage: string;
  keywordAnalyzer: string;
  modelGatewayMode: "external";
  embeddingProviderBaseUrl: string;
  embeddingProviderApiKey: string;
  rerankProviderBaseUrl: string;
  rerankProviderApiKey: string;
  llmProviderBaseUrl: string;
  llmProviderApiKey: string;
  embeddingDimension: number;
  embeddingModel: string;
  rerankModel: string;
  llmModel: string;
  llmFallbackModel: string;
  llmTemperature: number;
  llmMaxTokens: number;
  llmFirstTokenTimeoutMs: number;
  llmTotalTimeoutMs: number;
  llmMaxRetries: number;
  llmRetryBackoffMs: number;
  llmEnableThinking: boolean;
  passwordMinLength: number;
  accessTokenTtlMinutes: number;
  refreshTokenTtlMinutes: number;
  jwtIssuer: string;
  jwtAudience: string;
  jwtSigningKeyRef: string;
  vectorTopK: number;
  keywordTopK: number;
  rerankInputTopK: number;
  rerankMinScore: number;
  finalContextTopK: number;
  maxContextTokens: number;
  chunkDefaultSizeTokens: number;
  chunkOverlapTokens: number;
  chunkStrategyMode: "heading_paragraph" | "fixed_tokens";
  chunkPreserveTables: boolean;
  chunkPreserveCodeBlocks: boolean;
  chunkPreserveContractClauses: boolean;
  maxFileMb: number;
  maxConcurrentJobs: number;
  embeddingBatchSize: number;
  indexBatchSize: number;
  queryEmbeddingEnabled: boolean;
  retrievalResultEnabled: boolean;
  finalAnswerEnabled: boolean;
  crossUserFinalAnswerAllowed: boolean;
  queryQpsPerUser: number;
  auditRetentionDays: number;
  auditQueryTextMode: "none" | "hash" | "plain";
  permissionDefaultVisibility: "department" | "enterprise";
  permissionCacheTtlSeconds: number;
  permissionWriteAccessBlockFirst: boolean;
  permissionBlockOldIndexRefs: boolean;
  permissionFailClosed: boolean;
  securityRequireCitation: boolean;
  securityBlockInternalPromptLeakage: boolean;
  securityBlockSecretRefLeakage: boolean;
  securityPiiRedactionEnabled: boolean;
  securityRedactLogs: boolean;
  securityRedactAuditSummary: boolean;
  timeoutQueryTotalMs: number;
  timeoutAuthPermissionMs: number;
  timeoutRewriteMs: number;
  timeoutEmbeddingMs: number;
  timeoutVectorSearchMs: number;
  timeoutKeywordSearchMs: number;
  timeoutRerankMs: number;
  timeoutContextMs: number;
  timeoutPostprocessMs: number;
  degradeRewriteTimeout: string;
  degradeEmbeddingTimeout: string;
  degradeVectorUnavailable: string;
  degradeKeywordUnavailable: string;
  degradeRerankTimeout: string;
  degradeLlmTimeout: string;
  degradeModelPoolOverloaded: string;
  degradeImportBacklog: string;
  observabilityMetricsEnabled: boolean;
  observabilityTraceEnabled: boolean;
  alertActiveConfigLoadFailed: number;
  alertPermissionViolationRate: number;
  alertDraftIndexExposureCount: number;
  alertImportFailureRate: number;
  alertWorkerQueueBacklog: number;
  alertLlmTimeoutRate: number;
}

export type SetupRequestPayload = {
  setup: Record<string, unknown>;
  config: Record<string, unknown>;
};
