<script setup lang="ts">
import PasswordResetModal from "@/features/users/PasswordResetModal.vue";
import RoleBindingModal from "@/features/users/RoleBindingModal.vue";
import UserDepartmentModal from "@/features/users/UserDepartmentModal.vue";
import UserFormModal from "@/features/users/UserFormModal.vue";
import UserListPage from "@/features/users/UserListPage.vue";
import type { UserManagementContext } from "@/features/users/userManagementContext";

const props = defineProps<{
  model: UserManagementContext["value"];
}>();
</script>

<template>
  <UserListPage
    :can-load-user-admin="props.model.canLoadUserAdmin"
    :can-manage-users="props.model.canManageUsers"
    :can-manage-roles="props.model.canManageRoles"
    :can-read-users="props.model.canReadUsers"
    :can-read-roles="props.model.canReadRoles"
    :can-read-departments="props.model.canReadDepartments"
    :busy="props.model.busy"
    :feedback="props.model.feedback"
    :search-form="props.model.searchForm"
    :users="props.model.users"
    :pagination="props.model.pagination"
    :page-size-options="props.model.pageSizeOptions"
    @refresh="props.model.refreshUserRoleAdminState"
    @create="props.model.openCreateUserModal"
    @edit="props.model.openEditUserModal"
    @departments="props.model.openUserDepartmentsModal"
    @roles="props.model.openUserRolesModal"
    @password="props.model.openPasswordResetModal"
    @delete="props.model.openDeleteUserModal"
    @search="props.model.searchUsers"
    @update:keyword="props.model.updateKeyword"
    @update:status="props.model.updateStatus"
    @update:page="props.model.updatePage"
    @update:page-size="props.model.updatePageSize"
  />

  <UserFormModal
    :mode="props.model.userModalMode"
    :selected-user="props.model.selectedAdminUser"
    :create-form="props.model.userCreateForm"
    :edit-form="props.model.userEditForm"
    :danger-form="props.model.userDangerForm"
    :department-keyword="props.model.departmentKeyword"
    :role-keyword="props.model.roleKeyword"
    :create-department-options="props.model.createUserDepartmentOptions"
    :initial-assignable-roles="props.model.initialAssignableRoles"
    :can-read-roles="props.model.canReadRoles"
    :show-high-risk-confirm="props.model.showHighRiskConfirm"
    :selected-user-is-system-admin="props.model.selectedAdminUserIsSystemAdmin"
    :busy="props.model.busy"
    :feedback="props.model.feedback"
    :can-create="props.model.canCreateAdminUser"
    :can-update="props.model.canUpdateSelectedAdminUser"
    :can-delete="props.model.canDeleteSelectedAdminUser"
    :format-department-label="props.model.formatDepartmentLabel"
    :format-role-label="props.model.formatRoleLabel"
    :format-role-list="props.model.formatRoleList"
    @close="props.model.closeUserModal"
    @create="props.model.submitCreateAdminUser"
    @update="props.model.submitPatchSelectedAdminUser"
    @delete="props.model.deleteSelectedAdminUser"
    @search-departments="props.model.refreshDepartmentOptionsFromSearch"
    @search-roles="props.model.refreshAssignableRoleOptionsFromSearch"
    @toggle-department="props.model.toggleCreateDepartment"
    @toggle-role="props.model.toggleCreateRole"
    @update:create-username="props.model.updateCreateUsername"
    @update:create-name="props.model.updateCreateName"
    @update:initial-password="props.model.updateInitialPassword"
    @update:password-confirm="props.model.updateCreatePasswordConfirm"
    @update:create-confirmed-high-risk="props.model.updateCreateConfirmedHighRisk"
    @update:edit-name="props.model.updateEditName"
    @update:edit-status="props.model.updateEditStatus"
    @update:confirmed-disable-admin="props.model.updateConfirmedDisableAdmin"
    @update:confirmed-delete="props.model.updateConfirmedDelete"
    @update:department-keyword="props.model.updateDepartmentKeyword"
    @update:role-keyword="props.model.updateRoleKeyword"
  />

  <UserDepartmentModal
    :open="props.model.userModalMode === 'departments'"
    :selected-user="props.model.selectedAdminUser"
    :selected-departments-for-display="props.model.selectedUserDepartmentsForDisplay"
    :selected-department-ids="props.model.selectedUserDepartmentIds"
    :department-keyword="props.model.departmentKeyword"
    :active-departments="props.model.activeDepartments"
    :user-department-form="props.model.userDepartmentForm"
    :selected-user-primary-department-will-change="props.model.selectedUserPrimaryDepartmentWillChange"
    :can-manage-departments="props.model.canManageDepartments"
    :can-save="props.model.canSaveSelectedUserDepartments"
    :busy="props.model.busy"
    :feedback="props.model.feedback"
    :pagination="props.model.selectedUserDepartmentPagination"
    :page-size-options="props.model.pageSizeOptions"
    :format-department-label="props.model.formatDepartmentLabel"
    :format-department-list="props.model.formatDepartmentList"
    @close="props.model.closeUserModal"
    @save="props.model.saveSelectedUserDepartments"
    @search-departments="props.model.refreshDepartmentOptionsFromSearch"
    @toggle-department="props.model.toggleSelectedUserDepartment"
    @update:department-keyword="props.model.updateDepartmentKeyword"
    @update:confirmed-replace-primary="props.model.updateConfirmedReplacePrimary"
    @update:page="props.model.updateUserDepartmentPage"
    @update:page-size="props.model.updateUserDepartmentPageSize"
  />

  <RoleBindingModal
    :open="props.model.userModalMode === 'roles'"
    :selected-user="props.model.selectedAdminUser"
    :bindings="props.model.selectedUserRoleBindings"
    :assignable-roles="props.model.assignableRoles"
    :active-departments="props.model.activeDepartments"
    :active-knowledge-bases="props.model.activeKnowledgeBases"
    :role-keyword="props.model.roleKeyword"
    :department-keyword="props.model.departmentKeyword"
    :knowledge-base-keyword="props.model.knowledgeBaseKeyword"
    :selected-scope-type="props.model.selectedRoleBindingScopeType"
    :role-binding-form="props.model.roleBindingForm"
    :can-manage-roles="props.model.canManageRoles"
    :can-manage-knowledge-bases="props.model.canManageKnowledgeBases"
    :can-add="props.model.canAddSelectedUserRole"
    :disabled-reason="props.model.roleBindingDisabledReason"
    :busy="props.model.busy"
    :feedback="props.model.feedback"
    :pagination="props.model.selectedUserRoleBindingPagination"
    :page-size-options="props.model.pageSizeOptions"
    :format-role-code-label="props.model.formatRoleCodeLabel"
    :format-role-binding-scope="props.model.formatRoleBindingScope"
    :format-role-label="props.model.formatRoleLabel"
    :format-role-scope-type="props.model.formatRoleScopeType"
    :format-department-label="props.model.formatDepartmentLabel"
    :format-knowledge-base-label="props.model.formatKnowledgeBaseLabel"
    @close="props.model.closeUserModal"
    @revoke="props.model.revokeSelectedUserRoleBinding"
    @add="props.model.addSelectedUserRoleBinding"
    @role-change="props.model.onRoleBindingRoleChange"
    @search-roles="props.model.refreshAssignableRoleOptionsFromSearch"
    @search-departments="props.model.refreshDepartmentOptionsFromSearch"
    @search-knowledge-bases="props.model.refreshKnowledgeBaseOptionsFromSearch"
    @update:role-keyword="props.model.updateRoleKeyword"
    @update:department-keyword="props.model.updateDepartmentKeyword"
    @update:knowledge-base-keyword="props.model.updateKnowledgeBaseKeyword"
    @update:scope-id="props.model.updateRoleScopeId"
    @update:confirmed-high-risk="props.model.updateRoleConfirmedHighRisk"
    @update:confirmed-remove-admin="props.model.updateRoleConfirmedRemoveAdmin"
    @update:page="props.model.updateUserRoleBindingPage"
    @update:page-size="props.model.updateUserRoleBindingPageSize"
  />

  <PasswordResetModal
    :open="props.model.userModalMode === 'password'"
    :selected-user="props.model.selectedAdminUser"
    :form="props.model.passwordResetForm"
    :busy="props.model.busy"
    :feedback="props.model.feedback"
    :can-reset="props.model.canResetSelectedUserPassword"
    @close="props.model.closeUserModal"
    @submit="props.model.submitPasswordReset"
    @update:new-password="props.model.updateResetPassword"
    @update:password-confirm="props.model.updateResetPasswordConfirm"
    @update:force-change-password="props.model.updateForceChangePassword"
    @update:confirmed="props.model.updatePasswordResetConfirmed"
  />
</template>
