import { useUserDepartmentBindings } from "@/features/users/useUserDepartmentBindings";
import { useUserModals } from "@/features/users/useUserModals";
import { useUserRoleBindings } from "@/features/users/useUserRoleBindings";
import { useUserAdminRuntimeActions } from "@/features/users/useUserAdminRuntimeActions";
import { useUserAdminState } from "@/features/users/useUserAdminState";
import { useUsers } from "@/features/users/useUsers";
import type { UserAdminRuntimeOptions } from "@/features/users/userAdminRuntimeTypes";

export function useUserAdminRuntime(options: UserAdminRuntimeOptions) {
  const {
    adminUsers,
    createUserDepartmentOptions,
    selectedAdminUserDetail,
    userAdminBusy,
    userAdminFeedback,
    userPagination,
    userSearchForm,
  } = useUserAdminState(options);

  const {
    canCreateAdminUser,
    canDeleteSelectedAdminUser,
    canResetSelectedUserPassword,
    canUpdateSelectedAdminUser,
    clearUserModalState,
    closeUserModal: closeUserModalBase,
    ensureDefaultCreateDepartmentSelection,
    passwordResetForm,
    resetCreateUserForm,
    selectedAdminUser,
    selectedAdminUserId,
    selectedAdminUserIsSystemAdmin,
    syncUserEditForm,
    toggleCreateDepartment,
    toggleCreateRole,
    userCreateForm,
    userDangerForm,
    userEditForm,
    userModalMode,
  } = useUserModals({
    adminUsers,
    busy: userAdminBusy,
    canManageUsers: options.canManageUsers,
    createUserDepartmentOptions,
    selectedAdminUserDetail,
  });

  const {
    canSaveSelectedUserDepartments,
    clearUserDepartmentBindingState,
    openUserDepartmentsModal: openUserDepartmentsModalBase,
    refreshSelectedUserDepartments,
    refreshSelectedUserDepartmentsPage,
    selectedUserDepartmentIds,
    selectedUserDepartmentPagination,
    selectedUserDepartments,
    selectedUserDepartmentsForDisplay,
    selectedUserDepartmentsForForm,
    selectedUserPrimaryDepartmentWillChange,
    syncSelectedUserDepartmentForm,
    toggleSelectedUserDepartment,
    updateSelectedAdminUserDepartments,
    userDepartmentForm,
  } = useUserDepartmentBindings({
    adminUsers,
    busy: userAdminBusy,
    canManageDepartments: options.canManageDepartments,
    canReadDepartments: options.canReadDepartments,
    ensureAccessToken: options.ensureAccessToken,
    feedback: userAdminFeedback,
    normalizeErrorMessage: options.normalizeErrorMessage,
    selectedAdminUser,
    selectedAdminUserDetail,
    selectedAdminUserId,
    userModalMode,
  });

  const {
    adminRoles,
    assignableRoles,
    canAddSelectedUserRole,
    clearUserRoleBindingState,
    initialAssignableRoles,
    onRoleBindingRoleChange,
    openUserRolesModal: openUserRolesModalBase,
    refreshAssignableRoleOptions,
    refreshAssignableRoleOptionsFromSearch,
    refreshSelectedUserRoleBindings,
    refreshSelectedUserRoleBindingsPage,
    resetRoleBindingForm,
    roleBindingDisabledReason,
    roleBindingForm,
    selectedCreateRoles,
    selectedRoleBindingKey,
    selectedRoleBindingScopeType,
    selectedRoleForBinding,
    selectedUserRoleBindingKeys,
    selectedUserRoleBindingPagination,
    selectedUserRoleBindings,
    selectNextAvailableRoleBindingTarget,
    syncRoleBindingScopeDefault,
  } = useUserRoleBindings({
    activeDepartments: options.activeDepartments,
    activeKnowledgeBases: options.activeKnowledgeBases,
    busy: userAdminBusy,
    canManageRoles: options.canManageRoles,
    canReadRoles: options.canReadRoles,
    ensureAccessToken: options.ensureAccessToken,
    feedback: userAdminFeedback,
    normalizeErrorMessage: options.normalizeErrorMessage,
    roleKeyword: options.roleKeyword,
    selectedAdminUser,
    selectedAdminUserId,
    selectedUserDepartmentsForForm,
    selectorPageSize: options.selectorPageSize,
    userCreateForm,
    userModalMode,
  });

  const {
    clearUserAdminState,
    openCreateUserModal,
    openDeleteUserModal,
    openEditUserModal,
    openPasswordResetModal,
    openUserDepartmentsModal,
    openUserRolesModal,
    refreshSelectedAdminUserDetail,
    refreshUserRoleAdminState,
    selectAdminUser,
  } = useUserAdminRuntimeActions({
    adminUsers,
    canLoadUserAdmin: options.canLoadUserAdmin,
    canManageKnowledgeBases: options.canManageKnowledgeBases,
    canReadDepartments: options.canReadDepartments,
    canReadRoles: options.canReadRoles,
    canReadUsers: options.canReadUsers,
    clearDepartmentOptions: options.clearDepartmentOptions,
    clearKnowledgeBaseOptions: options.clearKnowledgeBaseOptions,
    clearUserDepartmentBindingState,
    clearUserModalState,
    clearUserRoleBindingState,
    ensureAccessToken: options.ensureAccessToken,
    ensureDefaultCreateDepartmentSelection,
    normalizeErrorMessage: options.normalizeErrorMessage,
    openUserDepartmentsModalBase,
    openUserRolesModalBase,
    passwordResetForm,
    refreshAssignableRoleOptions,
    refreshDepartmentOptions: options.refreshDepartmentOptions,
    refreshKnowledgeBaseOptions: options.refreshKnowledgeBaseOptions,
    refreshSelectedUserDepartments,
    refreshSelectedUserRoleBindings,
    resetCreateUserForm,
    roleBindingForm,
    selectNextAvailableRoleBindingTarget,
    selectedAdminUser,
    selectedAdminUserDetail,
    selectedAdminUserId,
    selectedRoleBindingKey,
    selectedUserDepartmentPagination,
    selectedUserDepartments,
    selectedUserRoleBindingKeys,
    selectedUserRoleBindingPagination,
    selectedUserRoleBindings,
    syncRoleBindingScopeDefault,
    syncSelectedUserDepartmentForm,
    syncUserEditForm,
    userAdminBusy,
    userAdminFeedback,
    userDangerForm,
    userDepartmentForm,
    userModalMode,
    userPagination,
    userSearchForm,
  });

  const {
    addSelectedUserRoleBinding,
    deleteSelectedAdminUser,
    revokeSelectedUserRoleBinding,
    saveSelectedUserDepartments,
    submitCreateAdminUser,
    submitPasswordReset,
    submitPatchSelectedAdminUser,
  } = useUsers({
    busy: userAdminBusy,
    closeUserModal,
    ensureAccessToken: options.ensureAccessToken,
    feedback: userAdminFeedback,
    isHighRiskAdminRole: options.isHighRiskAdminRole,
    normalizeErrorMessage: options.normalizeErrorMessage,
    passwordResetForm,
    refreshSelectedAdminUserDetail,
    refreshUserRoleAdminState,
    resetCreateUserForm,
    roleBindingForm,
    selectNextAvailableRoleBindingTarget,
    selectedAdminUser,
    selectedAdminUserId,
    selectedAdminUserIsSystemAdmin,
    selectedCreateRoles,
    selectedRoleForBinding,
    selectedUserDepartments,
    selectedUserDepartmentPagination,
    selectedUserPrimaryDepartmentWillChange,
    selectedUserRoleBindingPagination,
    selectedUserRoleBindings,
    syncRoleBindingScopeDefault,
    syncSelectedUserDepartmentForm,
    syncUserEditForm,
    updateSelectedAdminUserDepartments,
    userCreateForm,
    userDangerForm,
    userDepartmentForm,
    userEditForm,
  });

  function closeUserModal(): void {
    closeUserModalBase();
    resetRoleBindingForm();
  }

  return {
    addSelectedUserRoleBinding,
    adminRoles,
    adminUsers,
    assignableRoles,
    canAddSelectedUserRole,
    canCreateAdminUser,
    canDeleteSelectedAdminUser,
    canResetSelectedUserPassword,
    canSaveSelectedUserDepartments,
    canUpdateSelectedAdminUser,
    clearUserAdminState,
    closeUserModal,
    createUserDepartmentOptions,
    deleteSelectedAdminUser,
    ensureDefaultCreateDepartmentSelection,
    initialAssignableRoles,
    onRoleBindingRoleChange,
    openCreateUserModal,
    openDeleteUserModal,
    openEditUserModal,
    openPasswordResetModal,
    openUserDepartmentsModal,
    openUserRolesModal,
    passwordResetForm,
    refreshAssignableRoleOptionsFromSearch,
    refreshSelectedAdminUserDetail,
    refreshSelectedUserDepartmentsPage,
    refreshSelectedUserRoleBindingsPage,
    refreshUserRoleAdminState,
    resetCreateUserForm,
    revokeSelectedUserRoleBinding,
    roleBindingDisabledReason,
    roleBindingForm,
    saveSelectedUserDepartments,
    selectAdminUser,
    selectedAdminUser,
    selectedAdminUserDetail,
    selectedAdminUserId,
    selectedAdminUserIsSystemAdmin,
    selectedCreateRoles,
    selectedRoleBindingScopeType,
    selectedUserDepartmentIds,
    selectedUserDepartmentPagination,
    selectedUserDepartments,
    selectedUserDepartmentsForDisplay,
    selectedUserPrimaryDepartmentWillChange,
    selectedUserRoleBindingPagination,
    selectedUserRoleBindings,
    submitCreateAdminUser,
    submitPasswordReset,
    submitPatchSelectedAdminUser,
    syncRoleBindingScopeDefault,
    toggleCreateDepartment,
    toggleCreateRole,
    toggleSelectedUserDepartment,
    userAdminBusy,
    userAdminFeedback,
    userCreateForm,
    userDangerForm,
    userDepartmentForm,
    userEditForm,
    userModalMode,
    userPagination,
    userSearchForm,
  };
}
